feature/issue 151/x list detail view
KSG-IT/ksg-nett pull request #154
Opened 2020-11-12 16:31 UTC by alexaor

Closes #151

2020-11-26 16:29 UTC, Lekesoldat submitted a review, later dismissed
shalom shalom, ta en titt?

2020-11-26 16:29 UTC, Lekesoldat commented on economy/static/economy/css/economy_common.css
> +    flex-flow: column;
flex direction maybe?

2020-11-26 16:29 UTC, Lekesoldat commented on economy/static/economy/css/economy_common.css
> +    flex-flow: row;
flex direction maybe?

2020-11-26 16:29 UTC, Lekesoldat commented on economy/static/economy/css/economy_common.css
> +    flex-flow: row;
flex direction maybe?

2020-12-03 17:25 UTC, tOgg1 requested changes
The code looks good. Some notes:

* All the flex views should most likely be grids or tables
* The dropdowns which mention "source" should probably mention people instead.
* The source dropdowns should probably not contain more information than the name of the person?
* The product dropdown should also have more concise contents.
* You can put negative order sizes.
* The titles of the "Krysseliste" seems to be consistently "None"?

We can also nitpick a bit on the design together if you'd like.

2020-12-03 17:25 UTC, tOgg1 commented on economy/static/economy/css/economy_common.css
> +.main-table {
It's slightly weird to name a flex-container "table".

If this is to be a tabular format, we should probably use a table element or a grid.

2020-12-03 17:25 UTC, tOgg1 commented on economy/static/economy/css/economy_common.css
> +.main-table {
It seems the flex views also do not align. See

![2020-12-03-181048_916x154_scrot](https://user-images.githubusercontent.com/3416694/101063745-78ea0780-3593-11eb-96da-53aa687055ec.png)

2020-12-03 17:25 UTC, tOgg1 commented on economy/views.py
> +            form_data = request.POST  # rewrite as model form so we can get validation?
This should be a form, yes.

2020-12-13 16:49 UTC, tOgg1 approved these changes

2020-12-13 16:52 UTC, merged