feature/sc-132/backend-module-for-events
KSG-IT/ksg-nett pull request #226
Opened 2021-12-05 18:00 UTC by oystebha

-feat(events): add model, schema and resolvers for Event, add to admin.

2021-12-05 19:01 UTC, alexaor requested changes
Good stuff, some minor model/fields comments

2021-12-05 19:01 UTC, alexaor commented on events/models.py
> +    participants = models.ManyToManyField(User, blank=True)
Think we might make the reverse relation a bit more clearer with a more explicit `related_name`, maybe something like this?
```suggestion
    participants = models.ManyToManyField(User, blank=True), related_name="attended_events"
```

2021-12-05 19:01 UTC, alexaor commented on events/schema.py
> +        return Event.objects.all()
```suggestion
        return Event.objects.all().order_by("-date")
```

2021-12-05 19:01 UTC, alexaor commented on events/models.py
> +    date = models.DateField(blank=True, null=True)
Is it better if this is a DateTime field? Then we could implicitly define the meeting time as well

2021-12-05 22:01 UTC, alexaor commented on events/models.py
> +    description = models.CharField(max_length=1024)
Make this a `TextField` instead of a `CharField`?

2021-12-07 17:50 UTC, oystebha commented
done @ all

2021-12-08 18:22 UTC, alexaor approved these changes
LGTM

2021-12-08 18:22 UTC, merged