Temp branch/profile page
KSG-IT/ksg-nett pull request #32
Opened 2018-11-04 18:36 UTC by alexaor

Screwed up on main branch so checked out a new one. No conflicts with develop on this one whereas the original branch had several conflicts.

2018-11-05 16:46 UTC, chdefrene requested changes

2018-11-05 16:46 UTC, chdefrene commented on users/models.py
> +    in_relationship = models.BooleanField(default=False)
Maybe put this as a `NullBooleanField`? I can see some cases where someone wouldn't want their relationship status shown

2018-11-05 16:46 UTC, chdefrene commented on users/urls.py
> +    path('current-user/edit/', views.edit_current_user), # replace with <int:user_id>/update?
The idea about current is that we can create a separate view that has access to much more information than the normal `id` (public) variant has. But I guess using `id` only across the whole site and adding a check for current works just as well 😊

2018-11-05 16:48 UTC, chdefrene commented on users/models.py
> +    in_relationship = models.BooleanField(default=False)
This could also be solved by adding a preference to hide/show relationship status, but then we would need a separate field/mechanism to handle this.

2018-11-11 17:40 UTC, chdefrene commented
![wat](https://user-images.githubusercontent.com/6738930/48316234-34bcf080-e5e1-11e8-8016-28075d69c7c4.gif)

2018-11-16 19:51 UTC, closed without merging

2018-11-16 19:52 UTC, alexaor commented
closed in favor of #35