Comment charfield on deposit model
KSG-IT/ksg-nett pull request #40
Opened 2018-11-20 00:04 UTC by alexaor

2018-11-20 00:05 UTC, alexaor commented
#36

2018-11-23 10:04 UTC, tOgg1 commented
This solution, by the way, interfers slightly with the original `Innskudd` at sg-nett.

At sg-nett, the column analagous to `comment` here is used for the person *submitting* the deposit, to add any additonal comment.

The idea with the "admin-comment(s)", which #36 references, is that any admin should be able to in addition add one (or more?) comments to the deposit outlining issues with it. Perhaps it should also be possible for the user making the deposit to comment back. Hence, we might opt for a solution with a new model `DepositComment` with a foreign key to `Deposit`? 

Regardless, this PR provides useful functionality, as we need the `comment` field regardless.

2018-11-23 10:04 UTC, trmdy requested changes
The max length is a bit short. If it is either increased, or ideally if the field is changed to a TextField, this PR is good to go.

2018-11-25 13:55 UTC, trmdy approved these changes

2018-11-25 13:57 UTC, merged